# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-06-03 10:18:53
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    Input_raster = arcpy.Raster("Aspect raster path")

    # Process: 1st filter (Focal Statistics) (ia)
    temp1 = ""
    _1st_filter = temp1
    temp1 = arcpy.ia.FocalStatistics(in_raster=Input_raster, neighborhood="Circle 5 CELL", statistics_type="MEDIAN", ignore_nodata="DATA", percentile_value=90)
    temp1.save(_1st_filter)


    # Process: Aggregate pixels (Aggregate) (sa)
    temp2 = ""
    Aggregate_pixels = temp2
    temp2 = arcpy.sa.Aggregate(in_raster=temp1, cell_factor=8, aggregation_type="MEDIAN", extent_handling="EXPAND", ignore_nodata="DATA")
    temp2.save(Aggregate_pixels)


    # Process: 2nd filter (Focal Statistics) (ia)
    temp3 = ""
    _2nd_filter = temp3
    temp3 = arcpy.ia.FocalStatistics(in_raster=temp2, neighborhood="Circle 4 CELL", statistics_type="MEDIAN", ignore_nodata="DATA", percentile_value=90)
    temp3.save(_2nd_filter)


    # Process: 3rd filter (Focal Statistics) (ia)
    temp4 = ""
    _3rd_filter = temp4
    temp4 = arcpy.ia.FocalStatistics(in_raster=temp3, neighborhood="Rectangle 3 3 CELL", statistics_type="MEDIAN", ignore_nodata="DATA", percentile_value=90)
    temp4.save(_3rd_filter)


    # Process: 4th filter (Focal Statistics) (ia)
    temp5 = ""
    _4th_filter = temp5
    temp5 = arcpy.ia.FocalStatistics(in_raster=temp4, neighborhood="Rectangle 3 3 CELL", statistics_type="MEDIAN", ignore_nodata="DATA", percentile_value=90)
    temp5.save(_4th_filter)


    # Process: To integer (Int) (3d)
    temp6 = ""
    arcpy.ddd.Int(in_raster_or_constant=temp5, out_raster=temp6)
    temp6 = arcpy.Raster(temp6)

    # Process: To polygon (Raster to Polygon) (conversion)
    Final_vector = "path\to\finalVector.shp"
    arcpy.conversion.RasterToPolygon(in_raster=temp6, out_polygon_features=Final_vector, simplify="SIMPLIFY", raster_field="VALUE", create_multipart_features="SINGLE_OUTER_PART", max_vertices_per_feature=None)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"path\to\Default.gdb"):
        Model()
